---
title: Carolina Cartography Collective
timezone: America/New_York
collections:
  projects:
    title: Projects
    output: true
  vieques-exhibits:
    title: Vieques Exhibits
    output: true
    permalink: /geovisualizing-vieques/:path/
sass:
  style: compressed
localization:
  mode: manual
  locale: en-US
  content_dir: _locales
  locales_set: ["en-US", "es"]